version: "3.9"
services:

  watchtower:
    image: containrrr/watchtower
    restart: always
    container_name: fula_updater
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_NO_PULL=false
      - WATCHTOWER_MONITOR_ONLY=false
      - WATCHTOWER_POLL_INTERVAL=36000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  go-fula:
    image: $GO_FULA
    restart: always
    container_name: fula_go
    volumes:
      - /media/${CURRENT_USER}/:/storage:rw,rshared
      - /var/run/dbus:/var/run/dbus
      - $WPA_SUPLICANT_PATH/wpa_supplicant.conf:$WPA_SUPLICANT_PATH/wpa_supplicant.conf
      - shared-volume:/internal
    network_mode: "host"
    devices:
       - /dev/fuse:/dev/fuse:rwm 
    cap_add:
      - ALL
    privileged: true
    depends_on:
      - fxsupport
    labels:
      - "com.centurylinklabs.watchtower.enable=true"     
  sugarfunge-node:
    image: $SUGARFUNGE_NODE
    restart: always
    container_name: fula_node
    depends_on:
      - fxsupport
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - shared-volume:/internal

  fxsupport:
    image: $FX_SUPPROT
    restart: always
    container_name: fula_fxsupport
    command: tail -F /dev/null
    volumes:
      - /media/${CURRENT_USER}/:/storage:rw,rshared
      - shared-volume:/internal 
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - watchtower      
volumes:
 shared-volume:
