version: "3.9"
services:

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    command: --interval 30  --cleanup --label-enable
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  go-fula:
    build: ./go-fula
    #image: functionland/go-fula:$GO_FULA_TAG
    volumes:
      - /media/${CURRENT_USER}/:/storage:rw,rshared
      - /var/run/dbus:/var/run/dbus
      - $WPA_SUPLICANT_PATH/wpa_supplicant.conf:$WPA_SUPLICANT_PATH/wpa_supplicant.conf
    network_mode: "host"
    cap_add:
      - ALL
    privileged: true
    depends_on:
      - fxsupport
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      
  sugarfunge-node:
    build: ./sugarfunge-node
    #image: functionland/go-fula:$GO_FULA_TAG
    depends_on:
      - fxsupport
    labels:
      - "com.centurylinklabs.watchtower.enable=true"	

  fxsupport:
    build: ./fxsupport
    #image: functionland/fxsupport:$FX_SUPPROT_TAG
    volumes:
      - /media/${CURRENT_USER}/:/storage:rw,rshared
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
