version: "3.9"
services:

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  app:
    image: golang
    volumes:
      - $MOUNT_PATH:/storage:rw,rshared
    depends_on:
      - fxsupport
    labels:
          - "com.centurylinklabs.watchtower.enable=true"

  fxsupport:
    build: ./fxsupport/
    volumes:
      - /home/${CURRENT_USER}:/host:rw,rshared
    labels:
      - "com.centurylinklabs.watchtower.enable=true"