version: "3.9"
services:

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /home/${CURRENT_USER}/.docker/config.json:/config.json
    command: --interval 30
    environment:
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_NO_PULL=false
      - WATCHTOWER_MONITOR_ONLY=false
    labels:
      - "com.centurylinklabs.watchtower.enable=true"



  fxsupport:
    image: smzahraee/fxsupport:$FX_SUPPROT_TAG
    volumes:
      - /home/${CURRENT_USER}:/host:rw,rshared
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
