name: Docker Image Go-Fula Test

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build_go_fula:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ORG_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the Docker images
        run: docker buildx create --name multiarch --driver docker-container --use --node multiarch0
      - name: Build go-fula
        run: cd ./docker && source env_test.sh && cd ./go-fula && bash ./build.sh
      - name: Download go-fula
        run: source ../env_test.sh && bash ./download_image.sh
